language: xslt
install:
- echo "Installed"
script:
- sh .travis/publish.sh
after_success:
- sh .travis/deploy.sh
env:
  global:
  - TITLE="Thunderbird User Guide"
  - WELCOME="Welcome to Thunderbird!"
  - TEMPLATE="orange"
  - VARIANT="tiles"
notifications:
  email:
on_success: always